- name: skilldiploma.service
  template:
    src: skilldiploma1.j2
    dest: /lib/systemd/system/skilldiploma.service
    owner: root
    group: root
    mode: '0644'
    #    follow: yes

- name: Reload daemon
  shell: systemctl daemon-reload

- name: Start wordpress.service
  shell: systemctl start skilldiploma.service
